### ISSUE TITLE
Remember my site filter settings

### ISSUE THREAD

**Issue by mlr** [scotthasbrouck/HackerSurf#11]
I think it'd be useful to save the user's job filter setting to use again when they return.  I did [some research](https://www.meteor.com/blog/2014/03/14/session-cookies) on how Meteor handles sessions, then found this: [meteor-persistent-session](https://github.com/okgrow/meteor-persistent-session), [blog post here](http://www.okgrow.com/posts/2014/06/06/meteor-persistent-session/). 

Do you know of a better way to do it or a way without introducing a dependency?  I've been using Meteor for like 12 hours, so I could be off base!

I could take a crack at this if you think it'd be a good addition.

**Comment by scotthasbrouck** [comment]
This looks like a solid way of doing a persistent session, good find! If you're interested in taking a crack at it, feel free!

**Comment by mlr** [comment]
See PR #12
