### ISSUE TITLE
Add Job Box

### ISSUE THREAD

**Issue by scotthasbrouck** [scotthasbrouck/HackerSurf#9]
http://www.jobbox.io/offers

**Comment by joaojeronimo** [comment]
:+1:

**Comment by pmor** [comment]
Hi @scotthasbrouck,

I'm the CTO at JOBBOX.io. Let me know if you need any help with this, we'd be happy to help.
Not sure it's useful to you, but we have an atom feed, and we're also getting a JSON API up and running.

**Comment by scotthasbrouck** [comment]
Hey Pedro! Thanks for offering to help. I actually finished the scrape code early and just pushed it up. I would imagine it would be good to write an Atom feed reader for HackerSurf, even though I am just scraping JOBBOX right now. There are probably a number of other sites with an atom feed. Feel free to send over any info you have on your feed

**Comment by pmor** [comment]
Hi,

Our atom is here: http://www.jobbox.io/offers.atom

Incidentally, our index page is paginated at 50 entries. If you want to scrape the rest, `<nav class="pagination">` contains all the links.
